# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [9]:
# Import torch
import torch


# Create random tensor
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.5598, 0.8600, 0.9462, 0.0466, 0.0712, 0.6361, 0.0346],
        [0.2688, 0.8148, 0.5460, 0.9142, 0.7391, 0.1327, 0.2429],
        [0.8903, 0.1092, 0.6246, 0.8653, 0.7436, 0.7624, 0.6815],
        [0.5248, 0.3682, 0.0537, 0.2730, 0.5832, 0.3300, 0.9790],
        [0.0072, 0.8171, 0.3138, 0.1902, 0.0514, 0.1338, 0.4685],
        [0.0405, 0.4329, 0.7883, 0.0409, 0.3232, 0.1497, 0.5154],
        [0.9794, 0.5645, 0.8607, 0.4383, 0.4081, 0.6277, 0.5803]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [12]:
# Create another random tensor
second_random_tensor = torch.rand(1,7)
print(second_random_tensor)

# Perform matrix multiplication 
second_random_tensor_transposed = torch.t(second_random_tensor)
result = random_tensor @ second_random_tensor_transposed
result

tensor([[0.0382, 0.2540, 0.5694, 0.2113, 0.6617, 0.5744, 0.3059]])


tensor([[1.2115],
        [1.3609],
        [1.7387],
        [1.0767],
        [0.6809],
        [1.0265],
        [1.5716]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [17]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x_random_tensor = torch.rand(7, 7)
y_random_tensor = torch.rand(1,7)

# Matrix multiply tensors
result = x_random_tensor @ y_random_tensor.t()
result

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [20]:
# Set random seed on the GPU

torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [29]:
# Set random seed

torch.manual_seed(1234)

# Create two random tensors on GPU

v_random_tensor = torch.rand(2,3)
b_random_tensor = torch.rand(2,3)



# Check the tensors on CPU
print("Tensor A (CPU):")
print(v_random_tensor)
print("Tensor B (CPU):")
print(b_random_tensor)

# Send the tensors to GPU
device =  "cuda" if torch.cuda.is_available() else "cpu"
v_random_tensor.to(device)
b_random_tensor.to(device)

# Check the tensors on GPU
print("Tensor A (GPU):")
print(v_random_tensor)
print("Tensor B (GPU):")
print(b_random_tensor)

Tensor A (CPU):
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
Tensor B (CPU):
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])
Tensor A (GPU):
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
Tensor B (GPU):
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [36]:
# Perform matmul on tensor_A and tensor_B

result = v_random_tensor @ b_random_tensor.t()
result, result.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [39]:
# Find max
max = torch.max(result)

# Find min
min  = torch.min(result)
min

tensor(0.3647)

### 9. Find the maximum and minimum index values of the output of 7.

In [41]:
# Find arg max
max_indices = torch.argmax(result)
max_indices

# Find arg min
min_indices = torch.argmin(result)
min_indices

tensor(0)


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [51]:
# Set seed
torch.manual_seed(7)


# Create random tensor

random_tensor = torch.randn(1, 1, 1, 10)

print(random_tensor)


# Remove single dimensions
torch.manual_seed(7)
squeed_tensor = torch.squeeze(random_tensor)

# Print out tensors and their shapes
squeed_tensor, squeed_tensor.shape

tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
            1.2324,  0.1382, -1.6822]]]])


(tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
          0.1382, -1.6822]),
 torch.Size([10]))